daemon:
    host: ${DAEMON_HOST}
    port: ${DAEMON_PORT}
    debug: ${DAEMON_DEBUG}
    # logficat le: /db/ipswd.log

database:
    driver: postgres
    name: postgres
    host: ${POSTGRES_HOST}
    port: ${POSTGRES_PORT}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    database: ${POSTGRES_DB}
